### PR TITLE
New validate equations

### PR DESCRIPTION
**Pull request by maurolepore**
This PR merges not into `master` but into another PR this one depends on: `Ensure-equations-are-lowercase`.

It adds a new function `validate_equations()` that helps validate equations, and also tests that all equations in the `equations` dataset are valid.

You may now call `validate_equations()` from inside any function that accepts equations from the user.

For example:

``` r
devtools::load_all()
#> ℹ Loading allodb

some_allodb_function_that_accepts_users_equations <- function(equations) {
  validate_equations(equations)
  
  # Do something interesting
}

valid <- c("dbh + 1", "h + 1")
some_allodb_function_that_accepts_users_equations(valid)

invalid <- c("dbh + 1", "h + bad")
try(some_allodb_function_that_accepts_users_equations(invalid))
#> Error : Every equation must be valid.
#> x Invalid: h + bad.
#> * Error: object 'bad' not found
```

<sup>Created on 2021-08-01 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

### CODE REVIEW

**Comment by gonzalezeb** [comment]
ok. Merging to the New-validate_equations branch

**Comment by gonzalezeb** [comment]
wait, now how these commits are transferred to the `master` branch?

**Comment by maurolepore** [comment]
The'll will be added to `master` when `Ensure-equations-are-lowercase` gets merged into `master`.

**Comment by maurolepore** [comment]
Ooops, nope -- I forgot to ask to merge this pull request FIRST. No problem, I'll re-submit and we can merge it into `master`.

**Pull request merged**
