### PR TITLE
Use continuous integration with GitHub actions

### PR DESCRIPTION
**Pull request by maurolepore**
This commit adds CI with GitHub Actions in preparation for a new
version of rOpenSci's dev guide that asks contributors to move
away from Travis CI.

It also add badge to README and render it.

The developers guide of rOpenSci states that a continous integration
service is required. As of today, the guide suggests Travis but
rOpenSci is about to remove mentions of Travis CI in favor of
GitHub actions.

See https://devdevguide.netlify.app/booknews.html; it says:
> 2021-01-12, remove mentions of Travis CI and link to Jeroen Ooms’ blog post about moving away from Travis.

--

Also, have you run `devtools::check()` recently? When I run it locally it fails to complete. This will likely block the package at the editor level and you'll be asked to fix it before passing it to reviewers. Here is an example of the kinds of checks that editors run:
https://github.com/ropensci/software-review/issues/421#issuecomment-766195350

For more details see https://devguide.ropensci.org/editorguide.html

### CODE REVIEW

**Comment by maurolepore** [comment]
FYI you can now go to the tab "Actions" and see all automated checks that are triggered on every commit pushed to a pull request or to the master branch (e.g. when merging a pull request).

https://github.com/forestgeo/allodb/actions

Notice that currently all checks fail. You can explore any check ([example](https://github.com/forestgeo/allodb/runs/1789105606?check_suite_focus=true)) and try figure out what needs to be fixed. If you are stuck I can help.

**Comment by gonzalezeb** [comment]
Yes, thanks Mauro I noticed the action tab. The main thing I don't understand is why there is a failure in re-building the vignette. 
If I check lines 65-73 in allodb-vignette.Rmd they run fine. About "koppen-raster" we don't use that resource anymore and it is not mentioned in allodb-vignette.Rmd so I am not sure why is brought up.

`Error: --- re-building ‘allodb-vignette.Rmd’ using rmarkdown
Quitting from lines 65-73 (allodb-vignette.Rmd) 
Error: Error: processing vignette 'allodb-vignette.Rmd' failed with diagnostics:
'koppenRaster' is not an exported object from 'namespace:allodb'
--- failed re-building ‘allodb-vignette.Rmd’`

**Comment by cpiponiot** [comment]
Yes, I'm working on the codes, I'll notify you when I'm done. For now, the problem @gonzalezeb mentioned has been solved but I still get other errors. I'll ask you @maurolepore when I can't understand something

**Comment by gonzalezeb** [comment]
I have written documentation for all datasets in R/data, but there is an error that I can't see when I use devtools:document() to update the documentation in man/. 
> devtools::document()
Updating allodb documentation
Loading allodb
Writing NAMESPACE
Writing equations.Rd
Writing missing_values.Rd
Writing sitespecies.Rd
Writing references.Rd
Error in dirname(path) : path too long
> 
so there must be an error after line 141 on R/data.R because all datasets after references are just not written...grrrrrr.. Maybe @maurolepore see the problem. I have tried all!

**Comment by maurolepore** [comment]
I fail to reproduce your problem :-( This is my output of `devtools::document()`:

```
> devtools::document()
Updating allodb documentation
Loading allodb
Writing NAMESPACE
Writing NAMESPACE
``` 

The "Error in dirname(path) : path too long" reminds me of a problem I faced recently elsewhere, by which a path to a file was too long, e.g. a/path/with/too/many/characters.csv (the real path was much longer than this).


--

FYI I see some problems in `devtools::check()`:

```
── R CMD check results ────────────────────────────────── allodb 1.0.0.9000 ────
Duration: 1m 32.2s

❯ checking tests ...
  See below...

❯ checking for portable file names ... WARNING
  Found the following files with non-portable file names:
    How to built allodb website.R
    not-package-stuff/graphs/evaluation_of_equations/Quercus rubra.png
    not-package-stuff/graphs/evaluation_of_equations/Quercus velutina.png
    not-package-stuff/graphs/evaluation_of_equations/Tilia americana.png
    not-package-stuff/graphs/sites/speulderbos/Larix_x marschlinsii.png
    not-package-stuff/graphs/sites/umbc/Cupressus_x leylandii.png
    not-package-stuff/old data/sites_info_from Ervan.csv
    not-package-stuff/koppen climates
    not-package-stuff/old data
  These are not fully portable file names.
  See section ‘Package structure’ in the ‘Writing R Extensions’ manual.

❯ checking for missing documentation entries ... WARNING
  Undocumented code objects:
    ‘genus_family’ ‘gymno_genus’ ‘koppenMatrix’ ‘missing_values_metadata’
    ‘scbi_stem1’ ‘shrub_species’ ‘sites_info’ ‘wsg’ ‘wsg_metadata’
  Undocumented data sets:
    ‘genus_family’ ‘gymno_genus’ ‘koppenMatrix’ ‘missing_values_metadata’
    ‘scbi_stem1’ ‘shrub_species’ ‘sites_info’ ‘wsg’ ‘wsg_metadata’
  All user-level objects in a package should have documentation entries.
  See chapter ‘Writing R documentation files’ in the ‘Writing R
  Extensions’ manual.

❯ checking top-level files ... NOTE
  Non-standard files/directories found at top level:
    ‘How to built allodb website.R’ ‘README_files’ ‘not-package-stuff’

❯ checking R code for possible problems ... NOTE
  illustrate_allodb: no visible binding for global variable ‘dbh’
  illustrate_allodb: no visible binding for global variable ‘agb’
  illustrate_allodb: no visible binding for global variable ‘equation’
  new_equations: no visible binding for global variable ‘ref_id’
  new_equations: no visible binding for global variable
    ‘dependent_variable’
  new_equations: no visible binding for global variable ‘equation_id’
  new_equations: no visible binding for global variable
    ‘independent_variable’
  new_equations : <anonymous>: no visible binding for global variable
    ‘Lon’
  new_equations : <anonymous>: no visible binding for global variable
    ‘Lat’
  new_equations: no visible binding for global variable ‘equations’
  resample_agb: no visible binding for global variable ‘resample’
  weight_allom : <anonymous>: no visible binding for global variable
    ‘Lon’
  weight_allom : <anonymous>: no visible binding for global variable
    ‘Lat’
  weight_allom: no visible binding for global variable ‘zone1’
  weight_allom : compare_koppen: no visible binding for global variable
    ‘zone2’
  Undefined global functions or variables:
    Lat Lon agb dbh dependent_variable equation equation_id equations
    independent_variable ref_id resample zone1 zone2

❯ checking Rd files ... NOTE
  prepare_Rd: equations.Rd:77-79: Dropping empty section \details

── Test failures ───────────────────────────────────────────────── testthat ────

> library(testthat)
> library(allodb)
> 
> test_check("allodb")
══ Failed tests ════════════════════════════════════════════════════════════════
── Failure (test-data.R:34:3): Exported datasets match known output ────────────
Results have changed from known value recorded in 'ref-sitespecies'.

old[1:1117] vs new[1:1117]
- "                   site             family                  genus"
+ "                   site             family               genus"
- "1          changbaishan           Pinaceae                  Abies"
+ "1          changbaishan           Pinaceae               Abies"
- "2          changbaishan           Pinaceae                  Abies"
+ "2          changbaishan           Pinaceae               Abies"
- "3          changbaishan         Araliaceae           Acanthopanax"
+ "3          changbaishan         Araliaceae        Acanthopanax"
- "4          changbaishan          Aceraceae                   Acer"
+ "4          changbaishan          Aceraceae                Acer"
and 1107 more ...

[ FAIL 1 | WARN 0 | SKIP 0 | PASS 82 ]
Error: Test failures
Execution halted

1 error ✖ | 2 warnings ✖ | 3 notes ✖
```

**Comment by cpiponiot** [comment]
Hi @maurolepore !
Have you pulled the latest allodb version? Most of those problems should have been solved by now.

**Comment by maurolepore** [comment]
My bad. I was pulling from the wrong fork. Thanks!


I now seem to indeed experience problems in the process of documenting the package. The checks don't pass that stage.

```r
> devtools::check()
Updating allodb documentation
Loading allodb
Writing NAMESPACE
Writing NAMESPACE
Writing scbi_stem1-ForestGEO-sites-used-in-allodb-Table-with-geographical-information-for-ForestGEO-sites-used-in-allodb-open-paren-n-equals-24-close-paren-.-More-details-can-be-found-in-the-accompanying-manuscript.-times-tick-sites_info-tick-colon-A-dataframe-with-geographical-data-for-24-extratropical-ForestGEO-sites-used-in-allodb..Rd
Warning in file(con, "wb") :
  cannot open file '/home/mauro/git/allodb/man/scbi_stem1-ForestGEO-sites-used-in-allodb-Table-with-geographical-information-for-ForestGEO-sites-used-in-allodb-open-paren-n-equals-24-close-paren-.-More-details-can-be-found-in-the-accompanying-manuscript.-times-tick-sites_info-tick-colon-A-dataframe-with-geographical-data-for-24-extratropical-ForestGEO-sites-used-in-allodb..Rd': File name too long
Error in file(con, "wb") : cannot open the connection
> 
```

**Comment by gonzalezeb** [comment]
There is a problem documenting the datasets that I have tried to solve but can't. Although I added documentation for the needed datasets in R/data (scbi_stem1, gymno_genus, etc), all help-files after [line 164](
) are not built. All datasets have the same format except those below line 164 which do not have " @family database datasets". I'm not sure that's the problem but I wanted to mention it. Any ideas?

**Pull request merged**
