### PR TITLE
TODO: Run goodpractice::gp()

### PR DESCRIPTION
**Pull request by maurolepore**
> Run automated tests: ... goodpractice::gp() (most exceptions will need to be justified by the author in the particular context of their package.), devtools::spell_check(). 
-- https://devguide.ropensci.org/editorguide.html

--

TODO: Address or justify:

```r
── GP allodb ───────────────────────────────────────────────────────────────────

It is good practice to

  ✖ write unit tests for all functions, and all package code
    in general. 93% of code lines are covered by test cases.

    R/illustrate_allodb.R:90:NA
    R/illustrate_allodb.R:91:NA
    R/illustrate_allodb.R:92:NA
    R/new_equations.R:123:NA
    R/new_equations.R:124:NA
    ... and 21 more lines

  ✖ avoid long code lines, it is bad for readability. Also,
    many people prefer editor windows that are about 80 characters
    wide. Try make your lines shorter than 80 characters

    R/est_params.R:71:1
    R/new_equations.R:172:1
    R/new_equations.R:186:1
    R/new_equations.R:194:1
    R/new_equations.R:202:1
    ... and 17 more lines

  ✖ fix this R CMD check NOTE: Namespaces in Imports field
    not imported from: ‘dplyr’ ‘raster’ ‘readr’ All declared Imports
    should be used.
  ✖ fix this R CMD check NOTE: Note: found 156 marked UTF-8
    strings
```

### CODE REVIEW

**Comment by gonzalezeb** [comment]
I am running goodpractice::gp() and reviewing/applying suggestions

**Comment by maurolepore** [comment]
Great! When shortening lines to 80 characters, remember to let RStudio help you by pressing Ctrl+Shift+/

See "Reflow Comment" at file:///usr/lib/rstudio/www/docs/keyboard.htm

**Comment by gonzalezeb** [comment]
I am not sure how to fix this error: "write unit tests for all functions, and all package code in general. 91% of code lines are
    covered by test cases.
Maybe @cpiponiot can run goodpractice and check the files.

**Comment by maurolepore** [comment]
Don't worry. 91% coverage is beyond acceptable (80%). You can ignore it. It's a good idea, however, to see which lines are not covered and see if it is important to cover them or not. If not, you may exclude them with special markers: https://covr.r-lib.org/#exclusion-comments.

**Comment by gonzalezeb** [comment]
I am stock with this NOTES, do I need to try to fix them before submitting?

 ✖ fix this R CMD check NOTE: Package listed
    in more than one of Depends, Imports, Suggests,
    Enhances: 'rmarkdown' A package should be listed in
    only one of these fields.

**I think this refers to the package knirt that is mentioned in Suggest and VignetteBuilder in DESCRIPTION (?)**


  ✖ fix this R CMD check NOTE: Namespaces in
    Imports field not imported from: 'dplyr' 'raster'
    'readr' All declared Imports should be used.

**I am not sure if we use 'raster' anymore and if it related to this note**

  ✖ fix this R CMD check NOTE: Note: found 156
    marked UTF-8 strings

**do we need to import the [utf8 package](https://www.rdocumentation.org/packages/utf8/versions/1.1.4) in order to cover this?**

**Comment by maurolepore** [comment]
I submitted two PRs that should address this issues. The exception is the last one:

```r
heavy_multiplication_x fix this R CMD check NOTE: Note: found 156
marked UTF-8 strings
```

Take no action. I'm not sure where it comes form but I suspect refers to strings in datasets which encoding different to UTF-8. That can happen with datasets that contain words in, say, Spanish. I have ths same note in other packages ([example](https://cran.rstudio.org/web/checks/check_results_r2dii.data.html)) and CRAN seems to be okay with it.

**Pull request merged**
